version: "3.8"
services:
    postgres:
        image: "postgres:16"
        ports:
            - "1900:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=netshop
